# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ASKWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ASKDialogWin(object):
    def setupUi(self, ASKDialogWin):
        ASKDialogWin.setObjectName("ASKDialogWin")
        ASKDialogWin.resize(393, 131)
        self.gridLayoutWidget = QtWidgets.QWidget(ASKDialogWin)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(1, 5, 391, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lb_indicator = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lb_indicator.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_indicator.setFont(font)
        self.lb_indicator.setText("")
        self.lb_indicator.setObjectName("lb_indicator")
        self.gridLayout.addWidget(self.lb_indicator, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.all_line_word = QtWidgets.QHBoxLayout()
        self.all_line_word.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.all_line_word.setContentsMargins(-1, 0, -1, -1)
        self.all_line_word.setSpacing(6)
        self.all_line_word.setObjectName("all_line_word")
        self.line_ask_word = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_ask_word.setReadOnly(True)
        self.line_ask_word.setObjectName("line_ask_word")
        self.all_line_word.addWidget(self.line_ask_word)
        self.line_ask_tord_trans = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_ask_tord_trans.setObjectName("line_ask_tord_trans")
        self.all_line_word.addWidget(self.line_ask_tord_trans)
        self.gridLayout.addLayout(self.all_line_word, 0, 0, 1, 3)
        self.AllButton = QtWidgets.QHBoxLayout()
        self.AllButton.setObjectName("AllButton")
        self.pb_verify = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_verify.setMaximumSize(QtCore.QSize(160, 16777215))
        self.pb_verify.setObjectName("pb_verify")
        self.AllButton.addWidget(self.pb_verify)
        self.gridLayout.addLayout(self.AllButton, 2, 0, 1, 3)

        self.retranslateUi(ASKDialogWin)
        QtCore.QMetaObject.connectSlotsByName(ASKDialogWin)

    def retranslateUi(self, ASKDialogWin):
        _translate = QtCore.QCoreApplication.translate
        ASKDialogWin.setWindowTitle(_translate("ASKDialogWin", "Dialog"))
        self.line_ask_tord_trans.setPlaceholderText(_translate("ASKDialogWin", "Translate"))
        self.pb_verify.setText(_translate("ASKDialogWin", "Проверить"))
