# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ASKWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ASKDialogWin(object):
    def setupUi(self, ASKDialogWin):
        ASKDialogWin.setObjectName("ASKDialogWin")
        ASKDialogWin.resize(376, 104)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ASKDialogWin)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 2, 291, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.AllLineWord = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.AllLineWord.setContentsMargins(0, 0, 0, 0)
        self.AllLineWord.setObjectName("AllLineWord")
        self.LineASKWord = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.LineASKWord.setReadOnly(True)
        self.LineASKWord.setObjectName("LineASKWord")
        self.AllLineWord.addWidget(self.LineASKWord)
        self.LineASKWordTrans = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.LineASKWordTrans.setObjectName("LineASKWordTrans")
        self.AllLineWord.addWidget(self.LineASKWordTrans)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ASKDialogWin)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(7, 57, 361, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.AllButton = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.AllButton.setContentsMargins(0, 0, 0, 0)
        self.AllButton.setObjectName("AllButton")
        self.PB_Cancellation = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PB_Cancellation.setObjectName("PB_Cancellation")
        self.AllButton.addWidget(self.PB_Cancellation)
        self.PB_Verify = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PB_Verify.setObjectName("PB_Verify")
        self.AllButton.addWidget(self.PB_Verify)
        self.PB_Next_words = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PB_Next_words.setObjectName("PB_Next_words")
        self.AllButton.addWidget(self.PB_Next_words)

        self.retranslateUi(ASKDialogWin)
        QtCore.QMetaObject.connectSlotsByName(ASKDialogWin)

    def retranslateUi(self, ASKDialogWin):
        _translate = QtCore.QCoreApplication.translate
        ASKDialogWin.setWindowTitle(_translate("ASKDialogWin", "Dialog"))
        self.LineASKWordTrans.setPlaceholderText(_translate("ASKDialogWin", "Translate"))
        self.PB_Cancellation.setText(_translate("ASKDialogWin", "Хз"))
        self.PB_Verify.setText(_translate("ASKDialogWin", "Проверить"))
        self.PB_Next_words.setText(_translate("ASKDialogWin", "Следующий"))
